name: contra_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  readmore: ^2.1.0
  neumorphic_container: ^0.0.1+2
  translator: ^0.1.7
  curved_navigation_bar: ^1.0.1
  cloud_firestore: ^2.3.0
  tinycolor: ^1.0.3
  firebase_core: ^1.2.1
  carousel_slider: ^3.0.0
  flutter_email_sender: ^5.0.2
  simple_animations: ^1.3.3
  firebase_auth: ^1.4.1
  flutter_launcher_name: ^0.0.1
  sqflite: ^1.3.1+1
  auto_size_text: ^2.1.0
  path: ^1.7.0
  google_nav_bar: ^5.0.5
  flutter_neumorphic: ^3.1.0
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0
  animated_text_kit: ^2.5.3
  animated_widgets: ^1.0.6
  http: ^0.13.3
  provider: ^4.3.3
  flushbar: ^1.10.4
  google_fonts: ^2.1.0
  email_validator: ^1.0.0
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

flutter_launcher_name:
  name: "Aarog"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/images/

  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/popins_regular.ttf
        - asset: assets/fonts/popins_light.ttf
          weight: 300
        - asset: assets/fonts/popins_bold.ttf
          weight: 700
        - asset: assets/fonts/popins_semibold.ttf
          weight: 600
        - asset: assets/fonts/popins_medium.ttf
          weight: 500
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

